Repository 1995parham/github-do-not-ban-us, pull requests merged in 2019-07, with the labels that each got.

#861 Update Readme
  README.md
Labels: waiting

#719 Mention Restriction Policy
  README.md
Labels: enhancement

#704 Github is maintained by humanity
  together/cjzz
Labels: invalid

#946 Translate for Korean devs
  README-AR.md
  README-CN.md
  README-DE.md
  README-ES.md
  README-FR.md
  README-GR.md
  README-HY.md
  README-IT.md
  README-KO.md
  README-NL.md
  README-PER.md
  README-PT-BR.md
  README-RU.md
  README-SR.md
  README-TR.md
Labels: waiting

#958 alirezanet - github is for everyone
  README.md
  together/alirezanet/ReadThis.cs
Labels: waiting

#1094 Add support!
  README.md
  together/404cn/github_for_everyone.go
Labels: invalid

#1140 Name added to the supporters list
  README.md
Labels: invalid
